version: '3.9'

services:
  app:
    container_name: spreadsheet-management-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    env_file:
      - .env
    restart: "unless-stopped"
    volumes:
      - .:/rails