apiVersion: v1
kind: Service
metadata:
  name: spreadsheet-management-service
spec:
  selector:
    app: spreadsheet-management-service
  ports:
    - protocol: TCP
      port: 80  # Port that the service will expose inside the cluster
      targetPort: 3000  # Port the Ruby app is listening on
  type: ClusterIP  # Only accessible within the cluster
